name: Build WorldSpecialDaysCountdown (PR)

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Any CPU]

    runs-on: windows-latest

    env:
      Solution_Name: WorldSpecialDaysCountdown.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    # Build the app
    - name: Build the app
      run: msbuild -m -v:diag -p:Configuration=$env:Configuration -p:Platform=$env:Platform $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
